{{- if and .Values.serviceAccount.enabled .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-agent
  namespace: {{ $.Release.Namespace }}
  annotations:
    {{ .Values.serviceAccount.awsRoleAnnotation }}: {{ .Values.serviceAccount.awsRoleArn }}
{{- end }}
