{{- range $.Values.awsAgentsConfigs }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $.Release.Name }}-{{.aws_account_id}}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $.Release.Name }}-{{.aws_account_id}}
spec:
  replicas: 1
  serviceName: aws-agent-service
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{.aws_account_id}}
  template:
    metadata:
      name: {{ $.Release.Name }}-{{.aws_account_id}}
      namespace: {{ $.Release.Namespace }}
      labels:
        app: {{ $.Release.Name }}-{{.aws_account_id}}
    spec:
{{- if $.Values.serviceAccount.enabled }}
      serviceAccountName: aws-agent
{{ end }}
      containers:
        - name: aws-agent
          image: {{ $.Values.image.registry}}/{{ $.Values.image.repository }}:{{ $.Values.image.tag }}
          args: ["-c", "/etc/aws-config/aws-agent.yaml"]
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          volumeMounts:
            - name: secrets-volume
              mountPath: /etc/aws-config/secrets
            - name: config-volume
              mountPath: /etc/aws-config
            - name: checkpoints
              mountPath: /opt/spyderbat/aws_agent/checkpoints
          resources:
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}


      volumes:
        - name: config-volume
          configMap:
            name: {{ $.Release.Name }}-{{.aws_account_id}}
        - name: secrets-volume
{{- if $.Values.awsSecretsManager.enabled }}
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: aws-agent
{{- else }}
          secret:
            secretName: aws-agent
{{- end }}
        - name: checkpoints
          hostPath:
            path: /opt/spyderbat/aws_agent/checkpoints
            type: DirectoryOrCreate
{{- end }}
