{{- if .Values.awsSecretsManager.enabled -}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: aws-agent-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    app: aws-agent
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: {{ .Values.awsSecretsManager.secretArn }}
        jmesPath:
          - path: "\"spyderbat_registration_key\""
            objectAlias: spyderbat_registration_key
{{- end }}
