{{- if or .Values.credentials.aws_access_key_id .Values.credentials.spyderbat_api_key  }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- with .Values.credentials -}}
{{- if .aws_access_key_id }}
  aws_access_key_id: {{ .aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .aws_secret_access_key | b64enc }}
{{- end }}
{{- if .spyderbat_api_key }}
  spyderbat_api_key: {{ .spyderbat_api_key | b64enc }}
{{- end }}
{{- end }}
{{- end  }}