{{- if or .Values.awsConfig.credentials.aws_access_key_id .Values.spyderbatConfig.api_key  }}
apiVersion: v1
kind: Secret
metadata:
  name: aws-agent-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- with .Values.awsConfig.credentials -}}
{{- if .aws_access_key_id }}
  aws_access_key_id: {{ .aws_access_key_id | b64enc }}
  aws_secret_access_key: {{ .aws_secret_access_key | b64enc }}
{{- end }}
{{- end }}
{{- with .Values.spyderbatConfig -}}
{{- if .api_key }}
  spyderbat_api_key: {{ .api_key | b64enc }}
{{- end }}
{{- end }}
{{- end  }}