{{- with .Values.serviceAccount }}
{{- if .create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{ .awsRoleAnnotation }}: {{ .awsRole }}
{{- end }}
{{- end }}