{{- range $.Values.awsAgentsConfigs }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $.Release.Name }}-{{.aws_account_id}}
  namespace: {{ $.Release.Namespace }}
data:
  aws-agent.yaml: |
    {{- . | toYaml | nindent 4 }}
    spyderbat_orc_url: {{ $.Values.spyderbat_orc_url }}
    cluster_name: {{ $.Values.clusterName }}
{{- end }}

